### ISSUE TITLE
Move to hash for ID

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/data-model#8]
Auto-incrementing IDs are only easy to use when on Relational Databases.  Since we're using mostly NoSQL, we need another way to generate IDs.

Proposal: Hash based on the unique keys

Pipeline = hash(Git URL)
Job = hash(Pipeline ID + Name)
Build = hash(Job ID + Number)
Platform = hash(Name + Version)

For hashing, we need to pick the algorithm. We want something that is unique enough to reduce collisions, but not too long that users will never be able to provide them (or need short links).

Examples:
```javascript
require('hash-obj')({'scm_url':'git@github.com:foo/bar.git#master'}, {'algorithm': 'sha1'})
// 166ddd7c8535601203fd463248576284bbf23f87
require('hash-obj')({'scm_url':'git@github.com:foo/bar.git#master'}, {'algorithm': 'sha256'})
// 75506ba9eda58af9569c1c99465914b92ff297c457390e4ce96964d85bfb7977
```

We should pick a library that has a limited number of dependencies (as it doesn't really need it).  Examples:
 - https://www.npmjs.com/package/hasha
 - https://www.npmjs.com/package/hash-obj
 - https://www.npmjs.com/package/cyphrd
 - https://www.npmjs.com/package/hash-util

Or we use crypto directly:
 - https://nodejs.org/api/crypto.html#crypto_hash_digest_encoding

**Comment by FenrirUnbound** [comment]
The `user` model isn't addressed in the proposition. Is it going to be as simple as performing a hash on the username?

**Comment by d2lam** [comment]
@FenrirUnbound Probably. That sounds reasonable to me.

**Comment by d2lam** [comment]
PlatformID should probably be a hash(name+version). Since every version is a different object, there will be collisions if we just do hash(name)

**Comment by stjohnjohnson** [comment]
@d2lam good catch, updated.
